export const POLYGONE_ROUTE = "POLYGONE_ROUTE";
export const POLYLINE_ROUTE = "POLYLINE_ROUTE";
export const PINPOINT_ROUTE = "PINPOINT_ROUTE";
export const TOGGLE_PERMANENT_ROUTE = "TOGGLE_PERMANENT_ROUTE";
export const ADD_POSITION = "ADD_POSITION";
