export let notifications = [
  {
    id: 1,
    isRead: false,
    type: "Status Update",
    date: "17:25",
    sender: "Einav",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info1",
  },
  {
    id: 2,
    isRead: true,
    type: "Status Update",
    date: "17:00",
    sender: "Roberto",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info34",
  },
  {
    id: 3,
    isRead: true,
    type: "Status Update",
    date: "17:25",
    sender: "Ramiro the cat",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info4",
  },
  {
    id: 4,
    isRead: true,
    type: "Note",
    date: "17:25",
    sender: "Mul",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info3",
  },
  {
    id: 5,
    isRead: true,
    type: "Note",
    date: "17:25",
    sender: null,
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info1",
  },
  {
    id: 6,
    isRead: false,
    type: "Status Update",
    date: "17:25",
    sender: "Eden",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info56",
  },
  {
    id: 7,
    isRead: false,
    type: "Note",
    date: "17:25",
    sender: "Asaf",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info76",
  },
  {
    id: 8,
    isRead: true,
    type: "Status Update",
    date: "17:25",
    sender: "Galileo galiley",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info31",
  },
  {
    id: 9,
    isRead: true,
    type: "Status Update",
    date: "17:25",
    sender: "God",
    senderEmail: "lala@lululu.com",
    notes: "Hello world",
    routeDetails: "Info2",
  },
];
